rootProject.name = "multi_agent_ide"

include(":multi_agent_ide")
include(":multi_agent_ide_lib")
include(":tracing_agent")
include(":runner_code")
include(":graphql")
include(":test_graph")
include(":persistence")
include(":jpa-persistence")
include(":tracing")
include(":utilitymodule")
include(":commit-diff-context")
include(":commit-diff-model")
include(":commit-diff-context-mcp")
include(":mcp-tool-gateway")
include(":libs-resolver")
include(":proto")
