package com.hayden.multiagentide.agent.decorator;

import com.hayden.acp_cdc_ai.acp.events.Events;
import com.hayden.multiagentide.service.InterruptSchemaGenerator;
import com.hayden.multiagentide.agent.AgentType;
import com.hayden.multiagentide.model.nodes.GraphNode;
import com.hayden.multiagentide.prompt.contributor.NodeMappings;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.jspecify.annotations.Nullable;
import org.springframework.stereotype.Component;

/**
 * Composes the AddMessage payload injected into a running ACP session when
 * the controller (or human) initiates an interrupt. The payload includes:
 * <ul>
 *   <li>Override schema ({@code SomeOf(InterruptRequest)}) generated by victools</li>
 *   <li>Human-supplied reason for the interrupt</li>
 *   <li>Relevant context for the decision</li>
 *   <li>Verbiage instructing the agent that its structured response type has changed</li>
 * </ul>
 *
 * <p>Also supports route-back schema injection for collector agents when the
 * controller approves a route-back decision (Story 7).</p>
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class InterruptAddMessageComposer {

    private final InterruptSchemaGenerator interruptSchemaGenerator;

    /**
     * Compose the interrupt AddMessage payload for injection into a running ACP session.
     *
     * @param event the interrupt request event containing reason, context, reroute target
     * @param node  the target graph node (used to resolve agent type for schema generation)
     * @return the composed message string for AddMessage injection
     */
    public String composeInterruptMessage(Events.InterruptRequestEvent event, GraphNode node) {
        String reason = event.reason() == null || event.reason().isBlank()
                ? "Interrupt requested by external actor."
                : event.reason();

        AgentType agentType = resolveAgentType(event.sourceAgentType(), node);
        String interruptSchema = agentType != null
                ? interruptSchemaGenerator.generateInterruptSchema(agentType)
                : null;

        StringBuilder message = new StringBuilder();
        message.append("## INTERRUPT: Your structured response type has changed\n\n");
        message.append("The controller has interrupted your current operation. ");
        message.append("You MUST now respond with an InterruptRequest instead of your normal routing response.\n\n");
        message.append("### Reason\n");
        message.append(reason).append("\n\n");

        if (event.contextForDecision() != null && !event.contextForDecision().isBlank()) {
            message.append("### Context\n");
            message.append(event.contextForDecision()).append("\n\n");
        }

        if (event.rerouteToAgentType() != null && !event.rerouteToAgentType().isBlank()) {
            message.append("### Routing Target\n");
            message.append("The controller has determined that this should be routed to agent type: **")
                    .append(event.rerouteToAgentType()).append("**\n\n");
        }

        if (interruptSchema != null) {
            message.append("### Override Schema (InterruptRequest)\n");
            message.append("Fill your response according to this schema:\n```json\n");
            message.append(interruptSchema);
            message.append("\n```\n");
        }

        return message.toString();
    }

    /**
     * Compose a route-back AddMessage payload for injection into a collector's running session.
     * Used when the controller approves a route-back decision during a conversation.
     *
     * @param routeBackSchemaJson the route-back schema JSON string
     * @param targetAgentType     the agent type being routed back to
     * @param reason              controller's reason for approving the route-back
     * @return the composed message string for AddMessage injection
     */
    public String composeRouteBackMessage(String routeBackSchemaJson, String targetAgentType, String reason) {
        StringBuilder message = new StringBuilder();
        message.append("## ROUTE-BACK: Your structured response type has changed\n\n");
        message.append("The controller has approved a route-back to a previous phase. ");
        message.append("You MUST now respond with the route-back request instead of your normal routing response.\n\n");

        if (reason != null && !reason.isBlank()) {
            message.append("### Reason\n");
            message.append(reason).append("\n\n");
        }

        if (targetAgentType != null && !targetAgentType.isBlank()) {
            message.append("### Routing Target\n");
            message.append("Route back to agent type: **").append(targetAgentType).append("**\n\n");
        }

        if (routeBackSchemaJson != null) {
            message.append("### Override Schema (Route-Back Request)\n");
            message.append("Fill your response according to this schema:\n```json\n");
            message.append(routeBackSchemaJson);
            message.append("\n```\n");
        }

        return message.toString();
    }

    /**
     * Resolve the AgentType from the event's sourceAgentType string, or fall back
     * to inferring from the GraphNode subtype via {@link NodeMappings#agentTypeFromNode}.
     */
    static @Nullable AgentType resolveAgentType(@Nullable String sourceAgentTypeStr, GraphNode node) {
        if (sourceAgentTypeStr != null && !sourceAgentTypeStr.isBlank()) {
            try {
                return AgentType.fromWireValue(sourceAgentTypeStr);
            } catch (IllegalArgumentException ignored) {
                // fall through to node-based resolution
            }
        }
        return NodeMappings.agentTypeFromNode(node);
    }
}
